version: '3.9'

services:
  neo4j:
    image: neo4j:5.19-community
    container_name: ekko_neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - '7474:7474' # HTTP UI
      - '7687:7687' # Bolt driver
    volumes:
      - neo4j_data:/data
    restart: unless-stopped

  backend:
    build: .
    container_name: ekko_backend
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      - neo4j
    ports:
      - '8000:8000'
    restart: unless-stopped

volumes:
  neo4j_data:
